import React from 'react';

export default function ExperimentResultsAnalysisModal({ analysis, onClose }) {
  if (!analysis) return null;

  const exportMarkdown = () => {
    const md = `# Results Analysis: ${analysis.experiment_name}
**Type:** ${analysis.experiment_type}
**Status:** ${analysis.status}
**Dataset:** ${analysis.dataset_name}

## 📊 Baseline vs Proposed Metric Analysis
${analysis.metrics_analysis.map(m => `- **${m.metric_name}**: Baseline=${m.baseline_value || 'N/A'}, Proposed=${m.proposed_value || 'N/A'} (Diff: ${m.abs_difference !== null ? m.abs_difference : 'N/A'}). ${m.interpretation}`).join('\n')}

## ⚖ Trade-off Detection
${analysis.tradeoffs.length === 0 ? '_No trade-offs detected._' : analysis.tradeoffs.map(t => `- **${t.tradeoff_type}**: ${t.description}`).join('\n')}

## 🧠 Hypothesis Assessment
- **RQ:** ${analysis.hypothesis_assessment.research_question || 'N/A'}
- **H0:** ${analysis.hypothesis_assessment.hypothesis_h0 || 'N/A'}
- **H1:** ${analysis.hypothesis_assessment.hypothesis_h1 || 'N/A'}
- **Status:** ${analysis.hypothesis_assessment.assessment_status}
- **Explanation:** ${analysis.hypothesis_assessment.academic_explanation}

## 📊 Evidence Strength
**Rating:** ${analysis.evidence_strength.rating} (${analysis.evidence_strength.score}/100)
${analysis.evidence_strength.factors.map(f => `- ✓ ${f}`).join('\n')}

## 📝 Safe Conclusion
${analysis.safe_conclusion}

## 🎯 Recommended Next Steps
${analysis.recommended_next_steps.map(s => `- ${s}`).join('\n')}

---
*Analysis based on student-entered empirical data. Generated by IntelliResearch Results Analysis Engine.*
`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Analysis_${analysis.experiment_id}.md`;
    a.click();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-start justify-center pt-20 sm:pt-24 pb-6 px-3 sm:px-4 bg-slate-950/85 backdrop-blur-md animate-fade-in overflow-y-auto">
      <div className="w-full max-w-4xl glass-card rounded-3xl p-6 sm:p-8 border border-indigo-500/30 bg-slate-950 shadow-2xl space-y-6 max-h-[calc(100vh-7rem)] overflow-y-auto custom-scrollbar relative text-xs text-slate-300">

        {/* HEADER */}
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-800 pb-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-300 font-mono font-bold text-[11px]">
                📊 RESULTS ANALYSIS
              </span>
              <span className={`px-3 py-1 rounded-full text-[11px] font-extrabold border ${
                analysis.evidence_strength.rating === 'STRONGER' ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' :
                analysis.evidence_strength.rating === 'MODERATE' ? 'bg-indigo-500/10 border-indigo-500/30 text-indigo-300' :
                'bg-amber-500/10 border-amber-500/30 text-amber-300'
              }`}>
                EVIDENCE STRENGTH: {analysis.evidence_strength.rating} ({analysis.evidence_strength.score}/100)
              </span>
            </div>
            <h2 className="text-xl font-black text-slate-100">{analysis.experiment_name}</h2>
            <p className="text-xs text-slate-400">
              Evaluated method <strong>{analysis.proposed_arch}</strong> against baseline <strong>{analysis.baseline_alg}</strong> on dataset <strong>{analysis.dataset_name}</strong> across {analysis.run_count} run(s).
            </p>
          </div>

          <button onClick={onClose} className="p-2 rounded-xl bg-slate-900 border border-slate-800 hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-all font-bold">
            ✕ Close
          </button>
        </div>

        {/* METRIC-BY-METRIC COMPARISON TABLE */}
        <div className="space-y-3">
          <h3 className="text-xs font-extrabold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
            <span>📈</span> Metric-by-Metric Empirical Analysis
          </h3>

          {analysis.metrics_analysis.length === 0 ? (
            <div className="p-6 rounded-2xl bg-slate-900/40 border border-slate-800 text-center text-slate-400 text-xs">
              No metrics recorded for this experiment yet.
            </div>
          ) : (
            <div className="overflow-x-auto rounded-2xl border border-slate-800">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-900 border-b border-slate-800 text-slate-400 font-bold text-[10px] uppercase">
                    <th className="p-3">Metric</th>
                    <th className="p-3">Baseline</th>
                    <th className="p-3">Proposed</th>
                    <th className="p-3">Abs Diff</th>
                    <th className="p-3">Rel Gain</th>
                    <th className="p-3">Interpretation</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800 bg-slate-950/60">
                  {analysis.metrics_analysis.map((m, idx) => (
                    <tr key={idx} className="hover:bg-slate-900/50 transition-all">
                      <td className="p-3 font-bold text-slate-200">{m.metric_name}</td>
                      <td className="p-3 font-mono text-slate-300">{m.baseline_value ? `${m.baseline_value} ${m.unit || ''}` : <span className="text-slate-500 italic">Not recorded</span>}</td>
                      <td className="p-3 font-mono font-bold text-indigo-300">{m.proposed_value ? `${m.proposed_value} ${m.unit || ''}` : <span className="text-slate-500 italic">Not recorded</span>}</td>
                      <td className="p-3 font-mono font-bold">
                        {m.abs_difference !== null ? (
                          <span className={m.is_improved ? 'text-emerald-400' : m.abs_difference === 0 ? 'text-slate-400' : 'text-rose-400'}>
                            {m.abs_difference > 0 ? `+${m.abs_difference}` : m.abs_difference}
                          </span>
                        ) : <span className="text-slate-500 italic">N/A</span>}
                      </td>
                      <td className="p-3 font-mono font-bold">
                        {m.rel_difference_pct ? (
                          <span className={m.is_improved ? 'text-emerald-300' : 'text-slate-400'}>{m.rel_difference_pct}</span>
                        ) : <span className="text-slate-500 italic">N/A</span>}
                      </td>
                      <td className="p-3 text-slate-300 max-w-xs leading-relaxed">{m.interpretation}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* TRADE-OFF DETECTION CARD */}
        {analysis.tradeoffs.length > 0 && (
          <div className="p-4 rounded-2xl bg-amber-950/20 border border-amber-500/30 space-y-2">
            <h4 className="text-xs font-extrabold text-amber-300 uppercase tracking-wider flex items-center gap-1.5">
              <span>⚖</span> Performance Trade-Off Detected
            </h4>
            {analysis.tradeoffs.map((t, idx) => (
              <div key={idx} className="space-y-1">
                <p className="text-slate-200 font-medium">{t.description}</p>
                <p className="text-[11px] text-amber-200/80 italic">{t.impact_assessment}</p>
              </div>
            ))}
          </div>
        )}

        {/* MULTI-RUN CONSISTENCY */}
        {analysis.multi_run_stats.length > 0 && (
          <div className="space-y-3">
            <h3 className="text-xs font-extrabold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
              <span>🔁</span> Multi-Run Consistency & Dispersion ({analysis.run_count} Runs)
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {analysis.multi_run_stats.map((s, idx) => (
                <div key={idx} className="p-4 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-2">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                    <span className="font-bold text-indigo-300">{s.metric_name}</span>
                    <span className="px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 text-[10px] font-mono font-bold">
                      {s.consistency_rating}
                    </span>
                  </div>
                  <div className="grid grid-cols-4 gap-2 text-center font-mono">
                    <div>
                      <span className="text-[9px] text-slate-500 uppercase block font-bold">Mean</span>
                      <span className="text-slate-200 font-bold">{s.mean}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-slate-500 uppercase block font-bold">Std Dev</span>
                      <span className="text-indigo-400 font-bold">±{s.std_dev}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-slate-500 uppercase block font-bold">Min</span>
                      <span className="text-slate-400">{s.min_val}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-slate-500 uppercase block font-bold">Max</span>
                      <span className="text-slate-400">{s.max_val}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* HYPOTHESIS ASSESSMENT */}
        <div className="p-5 rounded-3xl bg-slate-900/80 border border-slate-800 space-y-3">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2">
            <h4 className="text-xs font-extrabold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
              <span>🧠</span> Hypothesis Assessment
            </h4>
            <span className={`px-3 py-1 rounded-full text-[11px] font-extrabold border ${
              analysis.hypothesis_assessment.assessment_status === 'CONSISTENT_WITH_H1' ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' :
              analysis.hypothesis_assessment.assessment_status === 'CONSISTENT_WITH_H0' ? 'bg-rose-500/10 border-rose-500/30 text-rose-400' :
              'bg-amber-500/10 border-amber-500/30 text-amber-300'
            }`}>
              {analysis.hypothesis_assessment.assessment_status.replace(/_/g, ' ')}
            </span>
          </div>

          <div className="space-y-2 text-xs">
            <p className="text-slate-300"><strong>Observed Findings:</strong> {analysis.hypothesis_assessment.observed_result_summary}</p>
            <p className="text-slate-400 italic"><strong>Academic Framing:</strong> {analysis.hypothesis_assessment.academic_explanation}</p>
          </div>
        </div>

        {/* SAFE CONCLUSION */}
        <div className="p-5 rounded-3xl bg-indigo-950/20 border border-indigo-500/30 space-y-2">
          <h4 className="text-xs font-extrabold text-indigo-300 uppercase tracking-wider flex items-center gap-1.5">
            <span>📝</span> Evidence-Based Plain-Language Conclusion
          </h4>
          <p className="text-slate-200 leading-relaxed font-medium">{analysis.safe_conclusion}</p>
        </div>

        {/* RECOMMENDED NEXT STEPS */}
        <div className="space-y-2">
          <h4 className="text-xs font-extrabold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
            <span>🎯</span> Recommended Next Steps
          </h4>
          <ul className="space-y-1.5">
            {analysis.recommended_next_steps.map((step, idx) => (
              <li key={idx} className="p-3 rounded-2xl bg-slate-900/60 border border-slate-800 text-slate-300 flex items-start gap-2.5">
                <span className="text-indigo-400 font-bold">→</span>
                <span>{step}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* FOOTER */}
        <div className="flex justify-between border-t border-slate-800 pt-4">
          <button onClick={exportMarkdown} className="px-4 py-2 rounded-2xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 font-bold text-xs flex items-center gap-1.5">
            <span>📝</span> Export Analysis Report (MD)
          </button>
          <button onClick={onClose} className="btn-primary py-2 px-5 text-xs font-bold">
            Done Reading
          </button>
        </div>

      </div>
    </div>
  );
}
